### ISSUE TITLE
Missing file during `make finish`

### ISSUE THREAD

**Issue by stdavids** [The-OpenROAD-Project/OpenROAD-flow#17] opened 2020-01-08 17:41 UTC
When running 'make finish' on the default design I get the following error message:

```
/home/vagrant/OpenROAD-flow/OpenROAD/build/src/magic: line 61: /home/vagrant/OpenROAD-flow/OpenROAD/lib/magic/tcl/magicdnull: No such file or directory
```

**Comment by rovinski** [comment] 2020-01-08 17:58
I noticed the magic files missing this morning and committed edf7173. Try pulling and see if the issue is fixed.

**Comment by rovinski** [comment] 2020-01-08 18:11
This was just fixed in

**Closed by rovinski** 2020-01-08 18:11 UTC
